version: 2.1
orbs:
  architect: giantswarm/architect@4.27.0

workflows:
  version: 2
  build:
    jobs:
      - architect/push-to-app-catalog:
          context: architect
          name: "push-to-default-app-catalog"
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "cilium-servicemonitors"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/