cluster:
  kubernetes:
    clusterDomain: cluster.local

team: kaas

# During initial tests of cilium in production, we are afraid we might have too many metrics scraped by prometheus.
# In order to avoid having stability issues, we allow disabling scraping of cilium by setting the disabled flag to true.
disabled: false

agent:
  scrapeInterval: 60s
  relabelings:
  - sourceLabels:
    - __meta_kubernetes_pod_node_name
    targetLabel: node
    replacement: ${1}
  metricRelabelings:
  # 'cilium_node_connectivity_latency_seconds' and 'cilium_node_connectivity_status' have too high cardinality
  # See note in doc: https://docs.cilium.io/en/stable/observability/metrics/#configuration
  - sourceLabels:
    - __name__
    regex: 'cilium_node_connectivity_latency_seconds'
    action: drop
  - sourceLabels:
    - __name__
    regex: 'cilium_node_connectivity_status'
    action: drop
hubble:
  scrapeInterval: 60s
  relabelings:
    - sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: node
      replacement: ${1}
  metricRelabelings: {}

operator:
  scrapeInterval: 60s
  relabelings: {}
  metricRelabelings: {}
