{{- if not .Values.disabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    application.giantswarm.io/team: {{ index .Chart.Annotations "application.giantswarm.io/team" | quote }}
    {{- include "cilium-servicemonitors.labels" . | nindent 4 }}
  name: cilium-agent
  namespace: kube-system
spec:
  endpoints:
  - honorLabels: true
    interval: {{ .Values.agent.scrapeInterval }}
    path: /metrics
    port: metrics
    {{- if .Values.agent.metricRelabelings }}
    metricRelabelings:
    {{- tpl (toYaml .Values.agent.metricRelabelings | nindent 4) . }}
    {{- end }}
    {{- if .Values.agent.relabelings }}
    relabelings:
    {{- tpl (toYaml .Values.agent.relabelings | nindent 4) . }}
    {{- end }}
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      k8s-app: cilium
{{- end }}
