{{- if not .Values.disabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    application.giantswarm.io/team: {{ .Values.team }}
      {{- include "cilium-servicemonitors.labels" . | nindent 4 }}
  name: cilium-operator
  namespace: kube-system
spec:
  endpoints:
  - honorLabels: true
    interval: {{ .Values.operator.scrapeInterval }}
    path: /metrics
    port: metrics
    {{- if .Values.operator.metricRelabelings }}
    metricRelabelings:
    {{- tpl (toYaml .Values.operator.metricRelabelings | nindent 4) . }}
    {{- end }}
    {{- if .Values.operator.relabelings }}
    relabelings:
    {{- tpl (toYaml .Values.operator.relabelings | nindent 4) . }}
    {{- end }}
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      io.cilium/app: operator
      name: cilium-operator
{{- end }}
